apiVersion: v1
kind: Secret
metadata:
  name: laravel
type: Opaque
data:
  APP_KEY: base64:kFwhue4KsyQF762mdppfdKxhbS+9vZVr5pI/u0FwHqw=
#stringData:
#  STRING_KEY: base64:kFwhue4KsyQF762mdppfdKxhbS+9vZVr5pI/u0FwHqw=
